import Head from 'next/head'
import { connectToDatabase } from "../util/mongodb";
import React, { useState, useEffect } from 'react';
// import styles from '../styles/Home.module.css';
// import '../styles/globals.css';
import Collection from './Collection';

/*
getServerSideProps establishes connection with MongoDB database
and returns destructured data
*/

export async function getServerSideProps() {
  
  //await connection to mongodb database
  const { db } = await connectToDatabase();

  //parse data
  const data = await db.collection("sample_photoApp").find({}).limit(20);
  const arrayData = await data.toArray();
  const parsedData = JSON.parse(JSON.stringify(arrayData));

  //return object props with parsed pata
  return {
    props: { properties: parsedData },
  }
}

//Home function returns html for Home page 
export default function Home({properties}) {

    // const [term, setTerm] = useState("")
    const [searchData, setSearchData] = useState({properties})
    // const [collection, setCollection] = useState({properties})
  
    useEffect (() => {
      // const search = async () => {
        // const { data } = await getServerSideProps();
        setSearchData({properties})
      // } 

    // if(searchData) {
    //   search()
    // }
   }, [])

    //every keypress re-renders component
    console.log({properties})

    return (
        <div>
          <Head>
            <title>Bob Reuter Photography Archive</title>
              <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main>
            <p>this is a test</p>
            <div className="columns-2xs gap-4 px-3">
              <div className=""></div>
                <Collection properties={properties}/>
              </div>
          </main>
          <footer>

          </footer>
        </div>
    )
  }